name: Debian-based Docker Image

on: [ push, workflow_dispatch ]

jobs:
  build:
    strategy:
      matrix:
        baseImage:
          - docker.io/library/debian:bullseye-slim
          - docker.io/library/debian:sid-slim
          - docker.io/library/ubuntu:jammy
          - docker.io/library/ubuntu:mantic
          - docker.io/library/ubuntu:noble
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      env:
        BASE_IMAGE: ${{ matrix.baseImage }}
      run: |
        repo_name="ghcr.io/pschichtel/dovecot"
        tmp_image_name="$repo_name:latest"
        podman build --build-arg BASE_IMAGE="$BASE_IMAGE" -t "$tmp_image_name" .
        codename="$(echo "$BASE_IMAGE" | cut -d':' -f2 | cut -d'-' -f1)"
        version="$(podman run --rm --entrypoint sh "$tmp_image_name" -c 'dovecot --version' | grep -Po '^\S+')"
        major_version="$(echo "$version" | cut -d'.' -f1)"
        podman tag "$tmp_image_name" "$repo_name:$codename" "$repo_name:$version-$codename" "$repo_name:$major_version-$codename"
        podman push "$repo_name:$codename"
        podman push "$repo_name:$version-$codename"
        podman push "$repo_name:$major_version-$codename"

