name: Debian-based Docker Image

on: [ push, workflow_dispatch ]

jobs:
  build:
    strategy:
      matrix:
        codename:
          - bullseye
          - bookworm
          - trixie
          - sid
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      env:
        DEBIAN_CODENAME: ${{ matrix.codename }}
      run: |
        repo_name="ghcr.io/pschichtel/dovecot"
        tmp_image_name="$repo_name:latest"
        podman build --buildarg DEBIAN_CODENAME="$DEBIAN_CODENAME" -t "$tmp_image_name" .
        version="$(podman run --rm --entrypoint sh "$tmp_image_name" -c 'dovecot --version | grep -Po "^\S+"')"
        major_version="$(echo "$version" | cut -d'.' -f1)"
        podman tag "$tmp_image_name" "$repo_name:$DEBIAN_CODENAME" "$repo_name:$version-$DEBIAN_CODENAME" "$repo_name:$major_version-$DEBIAN_CODENAME"
        podman push "$repo_name:$DEBIAN_CODENAME"
        podman push "$repo_name:$version-$DEBIAN_CODENAME"
        podman push "$repo_name:$major_version-$DEBIAN_CODENAME"

